version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.3
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.3
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

# 초기 실습에서는 Spark를 local[*] 모드로 실행해 Kafka 연동과 스트리밍 처리 흐름을 먼저 검증
# 이후 운영형 구조에서는 Spark master/worker 또는 클러스터 환경으로 분리할 수 있도록 Docker Compose 확장을 고려
  spark-master:
    image: apache/spark:3.5.3
    environment:
      - SPARK_MODE=master
    ports:
      - "8080:8080"
      - "7077:7077"

  spark-worker:
    image: apache/spark:3.5.3
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=8G    # 32GB 중 8GB 할당
      - SPARK_WORKER_CORES=4      # i7 8코어 중 4코어 할당
    depends_on:
      - spark-master


  postgres:
    image: postgres:16
    container_name: ny_taxi_postgres
    environment:
      POSTGRES_DB: nytaxi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: